### PR TITLE
chore: add bazel tests

### PR DESCRIPTION
**Pull request by andrewkatson**
This is just the initial commit to let @zaucy know that I am working on this module next. I am wondering on your thoughts on this error. I know what it is trying to say but afaik I am including the dependency right in the `MODULE.bazel` file and the `test/MODULE.bazel` file references the former correctly.

```
ERROR: Error computing the main repository mapping: in module dependency chain <root> -> boost.spirit@_ -> boost.type_traits@1.83.0.bzl.1: module not found in registries: boost.type_traits@1.83.0.bzl.1
```

Also this happens with every dependency. The top level builds just fine.

### CODE REVIEW

**Comment by zaucy** [comment]
Is the error happening in the test module? If so it just looks like you're missing a `.bazelrc` in the test directory.

**Comment by andrewkatson** [comment]
Oh duh that was it. What do I do about there being no real test files with this module? There is `test_headers/test.cpp` but that doesn't seem like an actual test.

**Comment by andrewkatson** [comment]
Nevermind I read the jamfile more closely and know how to test it!

**Comment by andrewkatson** [comment]
Okay so here is the issue I need help solving. The way to test is to do a `defines = ["BOOST_TEST_HEADER=include/boost/include/spirit/some_file.hpp"]` in each `cc_test` rule so that the `test.cpp` file tries to include each header defined by the glob in the jamfile. The issue is that you can't do up level references like `../include/boost/include/spirit/some_file.hpp` in the `srcs` attribute of each `cc_test`. I have uploaded what I have so far so let me know what you think!

**Comment by zaucy** [comment]
Is there a reason `BOOST_SPIRIT_HEADER_NAME` can't be `boost/include/spirit/some_file.hpp` (removed the `include/` prefix)? That way the header is already included by `@boost.spirit//:boost.spirit` in `hdrs` and you don't need to include it in the `srcs`.

**Comment by andrewkatson** [comment]
Oh yeah... Did that and it got me new errors so I will forge ahead. Thank you!

**Comment by andrewkatson** [comment]
@zaucy Can you add the CI workflow? Or is there a way I can add it?

**Comment by zaucy** [comment]
Its the yaml file in the `.githib` folder. Ill be able to get to it today!

**Comment by andrewkatson** [comment]
Sounds good! Thank you for the pointer

**Comment by zaucy** [comment]
CI added!

**Comment by andrewkatson** [comment]
All the tests pass now!

**Review by zaucy — APPROVED** [review]

**Comment by andrewkatson** [comment]
Let me know when you update the registry so I can move onto serialization.

**Comment by zaucy** [comment]
its released!

**Comment by andrewkatson** [comment]
Thank you!

**Pull request merged**
